### ISSUE TITLE
diverging implicits

### ISSUE THREAD

**Issue by drdozer** [tek/splain#11]
I've got a bunch of 'diverging implicit expansion' problems. Is there any way that splain could show me clearer details about this? The stack of implicits up to the divergence, and the divergent options?

**Comment by tek** [comment]
divergence goes through a shitload of private objects and functions with no easy override possibility, so this is probably not happening soon…it would require copying half of the typer's code into the plugin.

**Comment by drdozer** [comment]
OK, thanks -- here's hoping dotty does better

**Comment by tribbloid** [comment]
@drdozer @tek I've recently found a bypass that allows capturing DIE error without modifying too much code. Can we move the discussion to the new ticket?
