### ISSUE TITLE
API/settings cleanup for new features added to 1.1.0

### ISSUE THREAD

**Issue by tribbloid** [tek/splain#117]
So here are all the option keywords introduced in the pre-release build:

```
    val enabled = "enabled" // use plugin instead of scalac compiler to generate error information 
    val enableAll = "all" // set all boolean features to "true"
    
    val typeReduction = "Vtype-reduction"

    val typeDefPosition = "Vtype-def-position"

    val typeDetail = "Vtype-detail" // integer value: 0 ~ 4

    val typeDiffsDetail = "Vtype-diffs-detail" // integer value: 1 ~ 3
```

that's too many and too difficult to memorize.

The easiest way to simplify it is probably allowing some of the options to take more values, e.g.:

- `enableAll` will be removed for being incompatible with -Vimplicits & -VtypeDiffs
- `enabled` will only take value false/true
  - `false` : plugin disabled, emit scalac errors, -Vimplicits & -VtypeDiffs still works tho.
  - `true` (DEFAULT) : plugin enabled, but features have to be enabled on demand
- `typeReduction` and `typeDefPosition` can fold into `typeDetail`, which now takes value 0 ~ 6
  - `1`/` ` (DEFAULT) : type info uses toString (same as pre-1.1.0)
  - `2`/`long` : type info uses toLongString
  - `3`/`long,existential` : `2` + append existential context
  - `4`/`long,existential,reduction` : `3` + explain type reduction process
  - `5`/`long,existential,reduction,position` : `4` + append type definition position in code
  - `6`/`long,existential,reduction,position,alias` : `5` + explain type aliases
- `typeDiffsDetail` can't be simplified further.
  - `1`/` ` (DEFAULT) : no augmentation (same as pre-1.1.0)
  - `2`/`disambiguation`: augment type info with disambiguation for both sides in `<found>|<required>` and infix types (e.g. `A =:= B`, `A <:< B`) in error message
  - `3`/`disambiguation,builtin`: append original found/required error info emitted by Scala compiler IF AND ONLY IF augmented type info from both sides are identical
  - `4`/`disambiguation,builtinAlways`: same as `3`, but always append

I'm not sure if this level of control is good enough, obviously, more refinement could be added by mapping every number in the setting to a feature bit that can be turned on & off on demand, but writing their testing matrices will be a nightmare.

@tek what do you think?

**Comment by tribbloid** [comment]
Just realized that `enabled=all/max` wont' be able to affect existing compiler settings (e.g. "Vimplicits" & "VtypeDiffs"), so they have to be removed

**Comment by tek** [comment]
Personally, I appreciate more granular configurability, but for the sake of accessibility I think it should be enough to document the simple and complex options separately with a disclaimer.

Regarding the test domain inflation issue, I guess it boils down with how you structure the pipeline of collecting the data and formatting it – if you manage to move the interaction with the the level options fully into the (pure) formatting part, it should be feasible to have that many combinations…just my intuition.

**Comment by tribbloid** [comment]
thanks a lot @tek , just revised `typeDetail` and `typeDiffsDetail`, I'll post the new README section here shortly.

This should be the last ticket of 1.1.0-RC0 release

**Comment by tribbloid** [comment]
Will add the following section into README:

# type detail (experimental)

The option `-P:splain:VtypeDetail:X` can take an integer from 1 to 6 to attach different kinds of details to type information in any error message.

- `1` (DEFAULT) : type info in short form, by using toString (same as pre-1.1.0)
- `2` = **long** : type info in long form, by using toLongString
- `3` = `2` + (**existential** : existential context)
- `4` = `3` + (**reduction** : explain type reduction process)
- `5` = `4` + (**position** : type definition position in code)
- `6` = `5` + (**alias** : explain type aliases, this generally contains duplicate information with `3`, it is only included for completeness)

In addition, multiple names of the detail kind (denoted by bold text in the above list) can be appended to the option value to enable it, e.g. `-P:splain:VtypeDetail:1,reduction,position` can attach type reduction process & type definition position while bypassing **long** and **existential**.

# type diffs detail (experimental)

The option `-P:splain:VtypeDiffsDetail:X` can take an integer from 1 to 4 to augment type diff errors with different kinds of details.

- `1` (DEFAULT) : no augmentation (same as pre-1.1.0)
- `2` = **disambiguation** : augment type info with disambiguation for both sides in `<found>|<required>` and infix types (e.g. `A =:= B`, `A <:< B`) in error message
- `3` = `2` + (**builtIn** : attach built-in found/required errors emitted by Scala compiler IF AND ONLY IF both sides of the error message are identical)
- `4` = `3` + (**builtInAlways** : ALWAYS attach original found/required error info, even if both sides of the error message are different)

In addition, multiple names of the detail kind (denoted by bold text in the above list) can be appended to the option value to enable it, e.g. `-P:splain:VtypeDiffsDetail:1,builtIn` can attach built-in errors while bypassing **disambiguation**.

@tek the patch & release countdown should be submitted shortly, it they look good to you

**Comment by tribbloid** [comment]
PR submitted, 1.1.0-RC0 countdown to publishing

actually why countdown? It is a release candidate, should be published ASAP

**Comment by tribbloid** [comment]
finished, will release 1.1.0-RC0 ASAP
