### ISSUE TITLE
Splain conflicting with paradise 3.0.0-M10

### ISSUE THREAD

**Issue by leonjones1974** [tek/splain#14]
Great plugin - it has helped me a load.
Unfortunately it has stopped working since I introduced v3 of the paradise plugin

### Scala version
- 2.12.4

### Config 1 
Causes macro expansion to fail with:
 "macro annotation could not be expanded (the most common reason for that is that you need to enable the macro paradise plugin; another possibility is that you try to use macro annotation in the same compilation run that defines it)"

```
 .settings(addCompilerPlugin("org.scalameta" % "paradise" % "3.0.0-M10" cross CrossVersion.full))
 .settings(addCompilerPlugin("io.tryp" % "splain" % "0.2.7" cross CrossVersion.patch))
```

### Config 2
Macro expansion works but I'm back to the standard implicit failure output when something cannot be summoned

```
  .settings(addCompilerPlugin("io.tryp" % "splain" % "0.2.7" cross CrossVersion.patch))
  .settings(addCompilerPlugin("org.scalameta" % "paradise" % "3.0.0-M10" cross CrossVersion.full))
```

**Comment by tek** [comment]
see https://github.com/tek/splain/issues/4.
this is sort of nondeterministic, maybe try shaking up your build config :)

**Comment by kubukoz** [comment]
scalameta paradise is deprecated, don't use it ;)

**Comment by tek** [comment]
fixed by https://github.com/scala/scala/pull/7785
