### ISSUE TITLE
use in interactive compiler?

### ISSUE THREAD

**Issue by fommil** [tek/splain#2]
This looks very useful. He you think it'd be possible to have the implicit messages wired up to the reporter to use range positions? I'd like to see if we could get this working in ensime for instant feedback.

**Comment by fommil** [comment]
(btw we have support for ensime compiler plugins now... so a different plugin could be used for the build vs ide)

**Comment by tek** [comment]
I'm open to anything, but the monkey-patching nature of the plugin makes it a pretty unreliable basis for use in wider application scales like ensime. @milessabin already suggested PRing this to the compiler itself, maybe that's a better foundation for the whole endeavour.
in any case, why don't you elaborate a bit, I haven't learned the dynamics of the reporter yet.

**Comment by andyscott** [comment]
+1 @tek Please PR this to scalac
