### ISSUE TITLE
Configuration for shortening types / better support for newtypes

### ISSUE THREAD

**Issue by mrdziuban** [tek/splain#24]
Would it be possible to add configuration for how much to shorten types in errors? Maybe just an int to denote the minimum number of package/path parts to keep, defaulting to 1? e.g. for a type `foo.bar.baz.Thing`, setting the value to 2 would print `baz.Thing` instead of just `Thing`.

This would make it a lot easier to use splain along with [newtypes](https://github.com/estatico/scala-newtype), which generate code like this:

```scala
@newtype case class WidgetId(toInt: Int)
// becomes
type WidgetId = WidgetId.Type
object WidgetId {
  type Base = Any { type WidgetId$newtype }
  trait Tag extends Any
  type Type <: Base with Tag
}
```

so any errors for the `WidgetId` type printed by splain always end up just saying `Type`.

**Comment by tek** [comment]
https://github.com/tek/splain#truncating-module-paths

please see if this is satisfying to you!

**Comment by mrdziuban** [comment]
Aha, I should have scrolled down further 🤦‍♂️ thank you!

**Comment by tek** [comment]
oh no, I just built this!

should be on maven is a few minutes/hours.

**Comment by mrdziuban** [comment]
Oh, I see! Well then thank you again -- I'll give it a shot!

**Comment by mrdziuban** [comment]
@tek just following up, this works great. I ended up using this flag:

```
-P:splain:rewrite:^(([^\\.]+\\.)*)([^\\.]+)\\.Type$/$3
```

to rewrite anything like `foo.bar.Baz.Test` into just `Baz`. Thanks for the quick fix and all your work on splain!

**Comment by tek** [comment]
it's my pleasure. thanks for the feedback! glad to here it's working out for you
