### ISSUE TITLE
Usage example for old scala versions does not work

### ISSUE THREAD

**Issue by mmatloka** [tek/splain#36]
Hi,
I have in the code the code from https://github.com/tek/splain#usage:
```
libraryDependencies += {
  val v = if (scalaVersion.value <= "2.12.4") "0.4.1" else "0.5.5"
  ("io.tryp" %% "splain" % v cross CrossVersion.patch).withConfigurations(Some("plugin->default(compile)"))
}
```
However it does not work for Scala 2.12.10 and 2.12.11. The code sample compares strings, so "1" is < "4" so it tries to use "0.4.1".

The problem appears explicitly on 2.12.11, because splain 0.4.1 was still released for 2.12.10.

**Comment by tek** [comment]
I noticed that last week but forgot to change it :slightly_smiling_face: 
thanks!

**Comment by tek** [comment]
updated the instructions and bumped the version. please give it a try!

**Comment by mmatloka** [comment]
thanks :) probably we need to wait a few minutes, 0.5.6 is not shown yet in the repos.

**Comment by mmatloka** [comment]
I would propose to add also a line for 2.11 :)

**Comment by mikolak-net** [comment]
Might I suggest a condition like `scalaVersion.value.replaceFirst(raw"\.(\d)$$",".0$1") <= "2.12.04"`? Ugly regex magic, I know, but it should work for affected versions.

**Comment by mmatloka** [comment]
btw `scalaVersion.value.split(".")` takes regexp as parameter, it should be e.g. `scalaVersion.value.split("\\.")`, otherwise it produces empty list

**Comment by joprice** [comment]
There's also a char overload to avoid the escaping `scalaVersion.value.split('.')` https://www.scala-lang.org/api/2.12.3/scala/collection/immutable/StringOps.html#split(separator:Char):Array[String]

**Comment by tek** [comment]
> Might I suggest a condition like `scalaVersion.value.replaceFirst(raw"\.(\d)$$",".0$1") <= "2.12.04"`? Ugly regex magic, I know, but it should work for affected versions (i.e. `2.10.x` and up).

right, I forgot about the ancient times

**Comment by tek** [comment]
now we're safe until 2.12.100 :slightly_smiling_face:

**Comment by tek** [comment]
@mmatloka don't forget to close if you're satisfied!

**Comment by mmatloka** [comment]
thanks! :)
