### ISSUE TITLE
No output from plugin

### ISSUE THREAD

**Issue by marko-asplund** [tek/splain#37]
I'm trying out splain plugin for troubleshooting an issue with implicits.
I've tried following the [usage notes](https://github.com/tek/splain/tree/c183b2665a6ae42a303f556f25ad2666a15a8c15#usage) in the README, but I can't get any output when compiling the code.

Should splain output debug info on STDOUT when the plugin is properly set up and I do issue `compile` for sbt?

I'm using sbt v1.3 and Scala v2.12 and added the following bits in my `build.sbt`
```
scalacOptions ++= Seq(
  "-P:splain:implicits:true"
)

addCompilerPlugin("io.tryp" % "splain" % "0.5.6" cross CrossVersion.patch)
```

Should this be enough to set up the plugin or is something else needed?

My project setup can be found here:
https://github.com/marko-asplund/play-json-derived-codecs-issue/tree/0db017b110f3ea71987a7269804443785fcde459/play-json-1

**Comment by tek** [comment]
splain only deals with compilation errors. if you want debug information, scalac has a builtin option `-Vimplicits`.

**Comment by marko-asplund** [comment]
thanks! 🙇‍♂️
