### ISSUE TITLE
Can it be used in maven or gradle?

### ISSUE THREAD

**Issue by tribbloid** [tek/splain#38]
If they are possible, should these examples be included in the documentation?

I intend to use it in a gradle project, please let me know if I can help

**Comment by tek** [comment]
I have no experience with those, but I'd be happy to add your findings to the docs!

**Comment by tribbloid** [comment]
Figured it out (in gradle kotlin script):

```

    dependencies {

         ....
        scalaCompilerPlugins("io.tryp:splain_${vs.scalaV}:0.5.8")
         ....
    }

    scalaCompileOptions.apply {

       additionalParameters = listOf(
             ....
            //splain
            "-P:splain:tree",
            "-P:splain:breakinfix:80",
            "-P:splain:bounds:true",
            "-P:splain:boundsimplicits:true",
            "-P:splain:keepmodules:2"
        )
   }
```

That sums it up. Ping me if you think this part deserves its own doc so I'll submit a PR

**Comment by tek** [comment]
absolutely!

**Comment by tribbloid** [comment]
done
