### ISSUE TITLE
Error message when assigning value of type A to Tuple[A]

### ISSUE THREAD

**Issue by felher** [tek/splain#40]
Hi there :)

Thank you very much for this plugin, it is really helpful!

I've stumbled upon one thing today, though:

`val a: Tuple1[String] = "blar"`

leads to the error message

`type mismatch; String|String`

Is there any way that this could be improved by noting that one of those is in a tuple, using `(String,)` or `Tuple1[String]` maybe?

**Comment by tek** [comment]
good point. and done!

**Comment by felher** [comment]
Great. Thank you!
