### ISSUE TITLE
No artifact io.tryp:splain_2.12.13:0.5.7 published to mvnrepository

### ISSUE THREAD

**Issue by adam-singer** [tek/splain#41]
Looking to bump a project to 2.12.13 and unable to find io.tryp:splain_2.12.13:0.5.7 on https://mvnrepository.com/artifact/io.tryp/splain. Version is missing from https://github.com/tek/splain/blob/master/build.sbt#L2.

**Comment by tek** [comment]
thanks! uploading now. please note that the latest version is `0.5.8`!

**Comment by adam-singer** [comment]
awesome, thanks! I guess you won't need https://github.com/tek/splain/pull/42 .. that was quick

**Comment by tek** [comment]
:smile:
