### ISSUE TITLE
Scala 2.12 support

### ISSUE THREAD

**Issue by sellout** [tek/splain#5]
(In case it’s not clear, I am _very_ excited about this plugin.)

Just noticed that there’s no 2.12 support yet (so I still can’t add it unconditionally to ~/.sbt).

**Comment by tek** [comment]
heh. 2.12 is available, you probably tried it while something broke during upload earlier this day.

**Comment by sellout** [comment]
Yep, sorry. It works.

I checked build.scala, but I didn’t realize that `scalaVersion` didn’t have to be in `crossScalaVersions`. I usually see something like `crossScalaVersions := Seq(scalaVersion.value, "2.11.8", "2.10.6"))`. Does `crossScalaVersions` default to `Seq(scalaVersion.value)`? Because I see you used `crossScalaVersions ++=` there.

**Comment by tek** [comment]
actually, I tried your variant yesterday, and `sbt-release` tried to publish twice for `2.12`, so I assumed that `scalaVersion` is included as default. Looking at `Defaults.scala` in sbt you can find
```sbt
derive(crossScalaVersions := Seq(scalaVersion.value)),
```
so that's settled :D
