### ISSUE TITLE
Release for 2.13.5

### ISSUE THREAD

**Issue by iamrecursion** [tek/splain#51]
A project that I work on loves using splain, but we're also eagerly awaiting a few fixes that have come with Scala 2.13.5. It'd be great if a splain release could be cut that is compatible with 2.13.5!

Are there any plans for doing so soon, or is more work needed? We can, of course, upgrade without splain, but it'd be better if we didn't have to.

**Comment by tek** [comment]
done! please wait patiently for Maven to to its thing!

**Comment by iamrecursion** [comment]
It's up! Thank you so much!
