### ISSUE TITLE
Add `word-wrapping` for long infix types

### ISSUE THREAD

**Issue by danslapman** [tek/splain#6]
Long type signatures (like shapeless's records) looks clumsy even with infix printing. How about supporting optional `word-wrapping` by type name?

E.g.
```scala
Int :: String :: HNil
```

will become
```scala
Int ::
String ::
HNil
```

**Comment by tek** [comment]
I've had that idea as well, I'll get on it on the weekend

**Comment by tek** [comment]
took a shot at it. please give it a spin!

**Comment by danslapman** [comment]
Unfortunately, it seems that types in found/required error messages does not break.

**Comment by tek** [comment]
yeah, that's a little more complicated, but I'll see what I can do

**Comment by tek** [comment]
alright, seems to just work, although the indentation is off. I'll take a look when I find the time
