### ISSUE TITLE
unit tests in splain 0.5.9 and scala 2.13.6 are different. Should they be unified?

### ISSUE THREAD

**Issue by tribbloid** [tek/splain#61]
Just one quick example, for the test "chain":

In scala 2.13.6:

```scala
object ImplicitChain
{
  trait I1
  trait I2
  trait I3
  trait I4
  trait II
  implicit def i1(implicit impPar7: I3): I1 = ???
  implicit def i2a(implicit impPar8: I3): I2 = ???
  implicit def i2b(implicit impPar8: I3): I2 = ???
  implicit def i4(implicit impPar9: I2): I4 = ???
  implicit def g(implicit impPar3: I1, impPar1: I4): II = ???
  implicitly[II]
}
```

In splain 0.5.9:

```scala
trait Low
{
  trait I1
  trait I2
  trait I3
  trait I4
  trait F[X[_]]
  implicit def lowI1: I1 = ???
  implicit def lowI2: I2 = ???
}

object ImplicitChain
extends Low
{
  type T1 = C *** D >:< (C with D { type A = D; type B = C })
  type T2 = D *** ((C >:< C) *** (D => Unit))
  type T3 = (D *** (C *** String)) >:< ((C, D, C) *** D)
  type T4 = C *** D *** C
  type T5 = D *** C >:< D
  type T6 = pol.Case.Aux[Int, String]
  type T7 = D >:< C >:< D
  implicit def i1(implicit impPar7: I3): I1 = ???
  implicit def i2a(implicit impPar8: I3): I2 = ???
  implicit def i2b(implicit impPar8: I3): I2 = ???
  implicit def i4(implicit impPar9: I2): I4 = ???
  implicit def t7(implicit impPar14: F[({type λ[X] = Either[Int, X]})#λ]): T7 = ???
  implicit def t5(implicit impPar13: pol.Case.Aux[Int, String]): T5 = ???
  implicit def t4(implicit impPar12: T5): T4 = ???
  implicit def t3a(implicit impPar11: T7): T3 = ???
  implicit def t3b(implicit impPar10: T4): T3 = ???
  implicit def f(implicit impPar4: I4, impPar2: T3): T2 = ???
  implicit def g(implicit impPar3: I1, impPar1: T2): T1 = ???
  implicitly[T1]
}
```

I assume this is caused by a few bugfixes introduced after 0.5.8.

Now the problem becomes: should the latest tests in our plugin BE A SUPERSET of scalac test?

If so, our tests should have identical format with tests in scalac, afterwards we can easily include their tests without rewriting them

The plugin is already in production, people expect upcoming changes not breaking any existing behaviour (unless for a good reason)

**Comment by tek** [comment]
sounds sensible!

**Comment by tribbloid** [comment]
From what I observed in AnalyzerSpec, it appears that the option "-Vimplicits -Vtype-diffs" should always be enabled when using the plugin, otherwise the entire output will be ignored by scalac. Is this correct?

**Comment by tek** [comment]
yep those are the options that activate splain

**Comment by tribbloid** [comment]
OK I have make most tests from scalac working, but not all:

![Screenshot from 2021-10-07 20-09-42](https://user-images.githubusercontent.com/3441413/136478471-fd328b8a-9be3-456c-86f5-0a1ac2b7dd8c.png)

All failures were caused by this scala macro issue:

https://github.com/scala/bug/issues/6393

It may justify circumventing it instead of solving it head on.

**Comment by tribbloid** [comment]
the ammonite interpreter instead of scala macro interpreter

**Comment by tribbloid** [comment]
What do you think of the following deduplicating format? Slightly shorter:

```
newSource1.scala:28: error: implicit error;
!I e: I1
i1a invalid because
!I p: I2
――i2 invalid because
  !I p: I3
――――i3a invalid because
    !I p: I4
――――――i4 invalid because ..............[1]
      !I p: I5
――――――――i5 invalid because
        !I p: I6
――――――――――i6a invalid because .........[2]
          !I p: I7
――――――――――――i7 invalid because
            !I p: I8
――――――――――――――i8 invalid because
              !I p: I9

――――――――――i6b invalid because .........[3]
          !I p: I8
――――――――――――i8 invalid because
            !I p: I9

――――i3b invalid because
    !I p: I4
――――――i4 invalid because ..............[see 1]

i1b invalid because
!I p: I6
――i6a invalid because .................[see 2]
――i6b invalid because .................[see 3]
  implicitly[I1]
            ^
```

**Comment by tek** [comment]
I'd expect this to only be significant for very few cases, but knock yourself out!

**Comment by tribbloid** [comment]
awww, if it is an English idiom it must be very old.

I have fixed all existing tests in scalac, the ground truths of the following 2 tests were deemed defective, and are corrected in this patch. These are:

- TreeSpec/verboseTree
- BasicSpec/bounds

Could you review the changes for these 2 cases and approve them?

**Comment by tribbloid** [comment]
They are used for scala version resolving that should be shared between submodules (at this moment there is only core, but you may have more in the future). gradle unfortunately doesn't have a native way to share script code across projects, so the buildSrc need to be compiled and become a dependency on the build classpath

I'll do 2 things:

- create a branch called v0.5/release pointing to our status quo master
- submit a squashed PR from the 1.0.0/gradle branch, after README is completed, and every part in sbt has a counterpart in gradle

**WARNING**, this PR will be huge. And if submitted as-is, will drastically change the way it is built/tested/published. It will no longer support sbt or specs2, only gradle & scalatest. Please take your time to verify that it is fully compatible with your toolchain

**Comment by tribbloid** [comment]
Merged, this ticket should be superseded by a new one for acceptance test improvement, closing
