### ISSUE TITLE
Switch to gradle for 1.0.0-2.13.6 release

### ISSUE THREAD

**Issue by tribbloid** [tek/splain#63]
it appears that the latest sbt 1.5.5 is still using scala 2.12.14. Due to its design flaw it will always cause a classpath contamination issue:

https://stackoverflow.com/questions/27886370/how-to-have-sbt-plugin-exclude-its-dependency

There is no hope to fix it. Since 1.0.0 is targeting scala 2.13.6+, I don't see a point for keep using it in production. We should switch to gradle which is much more stable.

I'll also seek to swap out specs2 with the more stable scalatest if necessary.

Please let me know what you think.

**Comment by tek** [comment]
does that mean sbt will pull in 2.12 libraries when building with 2.13?

**Comment by tribbloid** [comment]
The entire scala 2.12 library was pulled on installation.

It is included in the classpath of the "project" submodule when being used, which seems to confuse a lot of IDE (IDEA, VSCode, bloop/metal). So technically it is not a "contamination", just an instance of autocompletion server not complex enough to segregate the two

**Comment by tek** [comment]
so we don't have to migrate?

**Comment by tek** [comment]
that's fine, go ahead. I haven't tried debugging with neovim

**Comment by tribbloid** [comment]
Thanks a lot, the die is cast. Closing
