### ISSUE TITLE
`noImplicitFoundError` API in AnalyzerPlugin doesn't have annotation message

### ISSUE THREAD

**Issue by tribbloid** [tek/splain#67]
When I try to enable 2 tests that uses implicit error messages. I found the following design flaw in the AnalyzerPlugin interface:

```
    override def noImplicitFoundError(param: Symbol, errors: List[ImplicitError], previous: String): String = {

      val convertedErrors = errors.map(convertError)

      val result = splainAnalyzer.formatImplicitError(
        param.asInstanceOf[splainAnalyzer.global.Symbol],
        convertedErrors,
        ""
      )

      result
    }
  }
```

As can be seen, the annotation argument in formatImplicitError is hardcoded to empty, causing all such messages to be ignored

This is because noImplicitFoundError doesn't provide it, furthermore it cannot be found anywhere. This is an example of a degrading quality of source code caused by premature integration of API

**Comment by tek** [comment]
yup!

**Comment by tribbloid** [comment]
Closing for integrated.

Just realised that this was my first time using the merge button, hope you don't mind. I promise to only do this after the review
