### ISSUE TITLE
Feature freeze for 1.0.0-RC1

### ISSUE THREAD

**Issue by tribbloid** [tek/splain#72]
Just proposing.

Also, can you compile on your computer? I can't do release on my own. I don't have the GPG key for the maven repo

**Comment by tek** [comment]
if you log into Sonatype Jira and go to this issue: https://issues.sonatype.org/browse/OSSRH-31099 you can ping an admin and ask them to add you to the project. they will then ask me to confirm.

**Comment by tribbloid** [comment]
No problem, but do you think it is safer this way?

They are a big machine, this may take some time.

ALSO, what other features are pending?

**Comment by tribbloid** [comment]
Can I ask another question? Do you always sign the jar before publishing.

For Open Source projects I think it is extra trouble, as it prevents your classes to be repackaged in another jar. But this seems to be a rule of Nexus repo manager:

https://github.com/gradle-nexus/publish-plugin/issues/122

I wonder if you have encounter this problem before>

**Comment by tek** [comment]
I've had no problems with it. the signing used to be done by `sbt-gpg`

**Comment by tribbloid** [comment]
no longer frozen after the release, case closed
