### ISSUE TITLE
Scala 2.13.7 release

### ISSUE THREAD

**Issue by rgugliel-da** [tek/splain#76]
Hi,
Is there any plans to release a version which is compatible with Scala 2.13.7?

Thanks!

Rafael

**Comment by tribbloid** [comment]
already on it: https://github.com/tek/splain/pull/75

1.0.0 can release for it without the test. But full test is obviously preferred

Would you like to patch it up?

**Comment by tribbloid** [comment]
@rgugliel-da @tek I've made a release of 1.0.0-RC1 to maven central, for both scala 2.13.6 & 2.13.7

Can any of you run a quick sanity check?

https://repo1.maven.org/maven2/io/tryp/splain_2.13.7/1.0.0-RC1/

**Comment by rgugliel-da** [comment]
Seems good on my side, thanks!

**Comment by tribbloid** [comment]
@rgugliel-da thanks a lot, please don't close it until all test cases are fixed

**Comment by tribbloid** [comment]
all test green on 2.13.7, will close in 1 week

**Comment by tribbloid** [comment]
its gone
