### ISSUE TITLE
enabling Plugin causes all members of package object "scala" to be undiscoverable in scala 2.13.7+

### ISSUE THREAD

**Issue by tribbloid** [tek/splain#81]
As indicated in the following test results:

https://github.com/tek/splain/actions/runs/1552235511

Even a simple line like:

```
List(1)
```

will confuses the modified typer, making it to throw some weird information:

```
object List is not a member of package scala
```

The defective typer was introduced by the following legacy code in ScalaPlugin.scala:

```
  val analyzerField = classOf[Global].getDeclaredField("analyzer")
  analyzerField.setAccessible(true)
  analyzerField.set(global, splainAnalyzer)

  val phasesSetMapGetter = classOf[Global]
    .getDeclaredMethod("phasesSet")

  val phasesSet = phasesSetMapGetter
    .invoke(global)
    .asInstanceOf[scala.collection.mutable.Set[SubComponent]]

  if (phasesSet.exists(_.phaseName == "typer")) {
    def subcomponentNamed(name: String) =
      phasesSet
        .find(_.phaseName == name)
        .head
    val oldScs @ List(oldNamer @ _, oldPackageobjects @ _, oldTyper @ _) = List(
      subcomponentNamed("namer"),
      subcomponentNamed("packageobjects"),
      subcomponentNamed("typer")
    )
    val newScs = List(splainAnalyzer.namerFactory, splainAnalyzer.packageObjects, splainAnalyzer.typerFactory)
    phasesSet --= oldScs
    phasesSet ++= newScs
  }
```

I wonder if there is a more elegant way to inject the splainAnalyzer without all these covfefe. But I can't remember their purpose when they were written.

@tek I wonder if you could give me a hint on which part of them is rendered redundant by the AnalyzerPlugin patch?

**Comment by tek** [comment]
none of this is needed to use the AnalyzerPlugin.

**Comment by tribbloid** [comment]
Yeah but some of the latest bugfix patches still need to inject splainAnalyzer. I'm talking about that scalac patch as an entirety, not just the class.

I've tried disabling part of that code, it fixes the compilation but break the test in 2.13.7:

https://github.com/tek/splain/runs/4477823515?check_suite_focus=true

**Comment by tek** [comment]
I took this mechanism from the macro paradise plugin, I don't think there's a better way to do it :frowning_face: 

Maybe some of the items in that `subcomponent` list have changed?

**Comment by tribbloid** [comment]
fixed: https://github.com/tek/splain/actions/runs/1565166520

PR on the way

**Comment by tek** [comment]
nice
