### ISSUE TITLE
Publish 1.0.1 for scala 2.13.9 & 2.13.10

### ISSUE THREAD

**Issue by tribbloid** [tek/splain#93]
patch already committed and passed all CI tests, how about publishing to maven central in the next 24 hours?

**Comment by tek** [comment]
go ahead!

**Comment by tribbloid** [comment]
done, will close after being indexed by mvnrepository

**Comment by tribbloid** [comment]
indexed: https://mvnrepository.com/artifact/io.tryp/splain

closing
